### ISSUE TITLE
Crashes when I go to another app

### ISSUE THREAD

**Issue by thatgeek95** [churichard/ru-direct#9]
On Google Nexus 6P running Android 7.0 with the November 2016 security patch, whenever I switch to another app, RU Direct crashes.

Not really sure what's going on here. Any ideas?

**Comment by jpaik** [comment]
Hey, not quite sure. I'm running Android 7.1.1 now and it seems to be working nominally when switching apps.

If you still have the problem, have you tried reinstalling or clearing the cache?

**Comment by thatgeek95** [comment]
I'm on 7.0.

Yeah I just tried reinstalling and clearing the cache to no avail. Still
crashes.

**Comment by jpaik** [comment]
Hmm @churichard, do you have any ideas?

**Comment by churichard** [comment]
Thanks for the bug report @thatgeek95! I apologize for the delay in responding to you.

I looked into it and it seems like it's not a problem with RU Direct. One of the Android updates broke the app, perhaps due to our use of the Google Maps API. Also, it might be specific to the Nexus 5X and 6P.

If you're interested, here's a description of the error that's happening: https://code.google.com/p/android/issues/detail?id=225500

In the meantime, I believe the latest version of Android (7.1.1) fixed this issue. Could you try updating Android and see if that fixes your issue? Thanks!

**Comment by thatgeek95** [comment]
I just got the update and it's working now.
Thanks!

**Comment by churichard** [comment]
Great! Thanks for using RU Direct :)
